---
config:
    treeView:
        showIcons: true
---

treeView-beta
    src/
        Hello.java
    bin/

%% ─ ━ (2500 - 2501)
%% │ ┃ (2502 - 2503)
%% └ ┕ ┖ ┗ (2514 - 2517)
%% ├ ┝ ┞ ┟ ┠ ┡ ┢ ┣ (251C - 2523)
